---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker
env:
  global:
    - AWS_ACCESS_KEY=
    - AWS_SECRET_KEY=
    - BUILD_REGION=us-east-2
    - DEPLOY_REGIONS="us-east-1,us-west-1,us-west-2"
    - IMAGE_VERSION=


# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip install --upgrade -r requirements-test.txt
script:
  - pre-commit run --all-files
