---
- hosts: all
  name: Setup base image
  become: yes
  become_method: sudo
  roles:
    - upgrade
    - python
    - banner
    - dev_ssh_access
    - persist_journald
    - htop
    - clamav
    - docker

- hosts: all
  name: Install bloodhound
  become: yes
  become_method: sudo
  roles:
    - bloodhound
  vars:
    # The password for Neo4j
    password: "{{ lookup('aws_ssm', '/neo4j/password') }}"

- hosts: all
  name: Install other Kali tools
  become: yes
  become_method: sudo
  roles:
    - kali
  vars:
    # The group that should own the tools installed to /target.  The
    # VNC user is in this group.
    group: kali-trusted

- hosts: all
  name: Install VNC
  become: yes
  become_method: sudo
  roles:
    - vnc
  vars:
    # The username, password, and ssh keys for the VNC user
    username: "{{ lookup('aws_ssm', '/vnc/username') }}"
    password: "{{ lookup('aws_ssm', '/vnc/password') }}"
    public_ssh_key: "{{ lookup('aws_ssm', '/vnc/ssh/rsa_public_key') }}"
    private_ssh_key: "{{ lookup('aws_ssm', '/vnc/ssh/rsa_private_key') }}"

- hosts: all
  name: Add VNC user to kali-trusted group
  become: yes
  become_method: sudo
  tasks:
    - name: Add VNC user to kali-trusted group
      user:
        append: yes
        groups:
          - kali-trusted
        name: "{{ username }}"
  vars:
    # The username for the VNC user
    username: "{{ lookup('aws_ssm', '/vnc/username') }}"

- hosts: aws
  name: AWS-specific roles
  become: yes
  become_method: sudo
  roles:
    - amazon_efs_utils
    - cloudwatch_agent
    # The instance types used for almost all the instances expose EBS
    # volumes as NVMe block devices, so that's why we need nvme here.
    - nvme
