---
- hosts: all
  name: Setup base image
  become: yes
  become_method: sudo
  roles:
    - upgrade
    - python
    - banner
    - dev_ssh_access
    - persist_journald
    - htop
    - kali
    # - clamav

- hosts: all
  name: Install bloodhound
  become: yes
  become_method: sudo
  roles:
    - bloodhound
  vars:
    # The password for Neo4j
    password: "{{ lookup('aws_ssm', '/neo4j/password') }}"

- hosts: all
  name: Install VNC
  become: yes
  become_method: sudo
  roles:
    - vnc
  vars:
    # The username and password for VNC
    username: "{{ lookup('aws_ssm', '/vnc/username') }}"
    password: "{{ lookup('aws_ssm', '/vnc/password') }}"

- hosts: aws
  name: AWS-specific roles
  become: yes
  become_method: sudo
  roles:
    # The instance types used for almost all the instances expose EBS
    # volumes as NVMe block devices, so that's why we need nvme here.
    - nvme
    # - cloudwatch_agent
